//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5044.27856)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at MINHTUAN on 11/12/2014 16:23:28 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using PhongHopKhongGiay.SRV.Entities;

namespace PhongHopKhongGiay.SRV.Data
{
    /// <summary>
    /// CAPPHEPVANPHONGDAIDIEN data access component. Manages CRUD operations for the CAPPHEPVANPHONGDAIDIEN table.
    /// </summary>
    public partial class PHONGHOPKHONGGIAYDAC : DatabaseFactories
    {
        private Database PhongHopKhongGiayDatabase;
        private Database ScheduleDatabase;
        public PHONGHOPKHONGGIAYDAC(IUnitOfWork unitOfWork)
        {
            PhongHopKhongGiayDatabase = unitOfWork.PhongHopKhongGiayDatabase;
            ScheduleDatabase = unitOfWork.ScheduleDatabase;
        }
        public List<DANHMUC> Load_DanhMuc(string Table)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteSprocAccessor<DANHMUC>("DM_Load_DanhMuc", Table).ToList();
            }
            catch (Exception ex)
            {
                return new List<DANHMUC>();
            }
        }

        public DataSet Load_USER_GetAllUsers(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("USER_GetAllUsers", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public List<THANHPHANCHUANBI> Load_DanhMucThanhPhanChuanBi(string Table)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteSprocAccessor<THANHPHANCHUANBI>("DM_Load_DanhMuc", Table).ToList();
            }
            catch (Exception ex)
            {
                return new List<THANHPHANCHUANBI>();
            }
        }
        public DataSet LH_Load_DanhSachTaiLieuCuocHopByLichHopID(long? LichHopID, string DoiTuongXemID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_DanhSachTaiLieuCuocHopByLichHopID", LichHopID, DoiTuongXemID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet Load_DanhSachTaiLieuByTempID(string IDTemp)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("CN_Load_DanhSachTaiLieuByIDTemp", IDTemp);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet CN_TAILIEU_UpdateLichHopIDByIDTemp(long? LichHopID, string IDTemp)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("CN_TAILIEU_UpdateLichHopIDByIDTemp", LichHopID, IDTemp);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet CN_TAILIEU_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("CN_TAILIEU_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_TAILIEUCUOCHOP_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUCUOCHOP_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }



        public DataSet LH_LichHop_InsUpDel(string objJson, string DoiTuongNhacLichHopID, string JsonThanhPhan, string JsonChuanBi)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LichHop_InsUpDel", objJson, DoiTuongNhacLichHopID, JsonThanhPhan, JsonChuanBi);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_ChuyenDuyet(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_ChuyenDuyet", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet CN_Load_DanhSachTaiLieuByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("CN_Load_DanhSachTaiLieuByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_Load_Schedule(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_Schedule", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_Load_Schedule_CaNhan(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_Schedule_CaNhan", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        
        public DataSet LH_Load_DanhSach_Schedule(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_DanhSach_Schedule", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadLichHopByLichHopID(string LichHopID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadLichHopByLichHopID", LichHopID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_ChuongTrinhHop_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_ChuongTrinhHop_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_BieuQuyet_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_BieuQuyet_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet DM_DANHMUC_InsUpDel(string objJson, string TenStore)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("DM_DANHMUC_InsUpDel", objJson, TenStore);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadBieuQuyetByLichHopID(string LichHopID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadBieuQuyetByLichHopID", LichHopID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_UpdateTinhTrangByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTinhTrangByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateTinhTrangByChuoiLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTinhTrangByChuoiLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateTinhTrangBatDauHoacKetThucLichHop(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTinhTrangBatDauHoacKetThucLichHop", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateTinhTrangPhatHanhByTaiLieuKetLuanID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTinhTrangPhatHanhByTaiLieuKetLuanID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateTimeDragAndDropSchedule(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTimeDragAndDropSchedule", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateShowShowKiosk(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateShowShowKiosk", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_LoadDataTable(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadDataTable", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_CheckTrungLichHopByUserID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_CheckTrungLichHopByUserID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GetPhongBanSuDung(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetPhongBanSuDung", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GetNguoiChuTriDangDieuHanhCuocHop(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetNguoiChuTriDangDieuHanhCuocHop", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_LoadChuongTrinhHopByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadChuongTrinhHopByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_THAOLUAN_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_THAOLUAN_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadThaoLuanByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadThaoLuanByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GIAYMOIHOP_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GIAYMOIHOP_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadGiayMoiHopByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadGiayMoiHopByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GetEmailThanhPhanThamDuTheoThoiGian(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetEmailThanhPhanThamDuTheoThoiGian", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_PhatHanh_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_PhatHanh_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadPhatHanhByThoiGian(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadPhatHanhByThoiGian", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_LoadNoiDungInAnTheoThoiGian(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadNoiDungInAnTheoThoiGian", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        
        public DataSet LH_GetLichHopIDTheoThoiGian(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetLichHopIDTheoThoiGian", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_PhatHanhLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_PhatHanhLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }


        public DataSet LH_LoadPhatHanhLichSuTheoThoiGian(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadPhatHanhLichSuTheoThoiGian", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_PhatHanhTrucTiep(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_PhatHanhTrucTiep", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_LH_LICHHOP_BAOVANG_Upd(int LichHopID, int UserID, int LyDoID, string NoiDungLyDo)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_LICHHOP_BAOVANG_Upd", LichHopID, UserID, LyDoID, NoiDungLyDo);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_LH_LICHHOP_XUNGDOT_Upd(int LichHopID, int UserID, int LyDoID, string NoiDungLyDo)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_LICHHOP_XUNGDOT_Upd", LichHopID, UserID, LyDoID, NoiDungLyDo);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_LH_LICHHOP_CHAPNHAN_Upd(int LichHopID, int UserID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_LICHHOP_CHAPNHAN_Upd", LichHopID, UserID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet Mobile_LH_LICHHOP_TUCHOIHOP_Upd(int LichHopID, int UserID, int LyDoID, string NoiDungLyDo)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_LICHHOP_TUCHOIHOP_Upd", LichHopID, UserID, LyDoID, NoiDungLyDo);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }


        public DataSet Mobile_LH_BIEUQUYET_KETQUA_Ins(int UserID, int BieuQuyetID, bool DongY)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_BIEUQUYET_KETQUA_Ins", UserID, BieuQuyetID, DongY);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_BIEUQUYET_GetByLichHopID(int LichHopID, int PageSize, int PageIndex, int UserID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_BIEUQUYET_GetByLichHopID", LichHopID, PageSize, PageIndex, UserID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet CN_Load_DanhSachTaiLieuByUserID(int UserID, long LichHopID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("CN_Load_DanhSachTaiLieuByUserID", UserID, LichHopID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_CN_TAILIEU_Ins(int UserID, int TaiLieuCuocHopID, long LichHopID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_CN_TAILIEU_Ins", UserID, TaiLieuCuocHopID, LichHopID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_CN_TAILIEU_CHIASE_Ins(int NguoiChiaSeID, int NguoiNhanChiaSeID, long TaiLieuChiaSeID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_CN_TAILIEU_CHIASE_Ins", NguoiChiaSeID, NguoiNhanChiaSeID, TaiLieuChiaSeID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_UpdateTinhTrangCuocHop(int BieuQuyetID, bool TinhTrang,bool DaKetThuc, long UserID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTinhTrangCuocHop", BieuQuyetID, TinhTrang, DaKetThuc, UserID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadDangKyPhatBieuTheoLichHopID(int LichHopID, long UserID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadDangKyPhatBieuTheoLichHopID", LichHopID, UserID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_DANGKYPHATBIEU_InsUpDel(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DANGKYPHATBIEU_InsUpDel", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }


        public DataSet LH_UpdateDoUuTienDangKyPhatBieu(string ChuoiDangKyPhatBieuID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateDoUuTienDangKyPhatBieu", ChuoiDangKyPhatBieuID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_UPDATE_THOIGIAN_DANGKYPHATBIEU(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UPDATE_THOIGIAN_DANGKYPHATBIEU", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadBienBanHopByLichHopID(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadBienBanHopByLichHopID", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_BIENBANHOP_InsUpDel(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_BIENBANHOP_InsUpDel", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GiaoViec_InsUpDel(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GiaoViec_InsUpDel", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GiaoViec_UpdateChiTietGiaoViec(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GiaoViec_UpdateChiTietGiaoViec", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadGiaoViecTheoLichHopID(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadGiaoViecTheoLichHopID", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_NOIDUNG_IN_AN_InsUpDel(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_NOIDUNG_IN_AN_InsUpDel", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_TRIGGER_SIGNALR(string obj)
        {
            try
            {
                return ScheduleDatabase.ExecuteDataSet("LH_TRIGGER_SIGNALR", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_InLichHopTheoTuan(string obj)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_InLichHopTheoTuan", obj);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_LoadChiTietBieuQuyetKetQuaTheoBieuQuyetID(int BieuQuyetID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadChiTietBieuQuyetKetQuaTheoBieuQuyetID", BieuQuyetID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_InKetLuanTheoLichHopID(int LichHopID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_InKetLuanTheoLichHopID", LichHopID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Mobile_LH_LICHHOP_DUYETBAOVANG_Upd(int LichHopID, int UserID, bool DuyetBaoVang, string LyDoKhongDuyet)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("Mobile_LH_LICHHOP_DUYETBAOVANG_Upd", LichHopID, UserID, DuyetBaoVang, LyDoKhongDuyet);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_TAILIEUKETLUAN_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUKETLUAN_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_CheckRoleByUserID(int UserID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_CheckRoleByUserID", UserID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_TAILIEUCUOCHOP_COQUANCHUTRI_GetByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUCUOCHOP_COQUANCHUTRI_GetByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_TAILIEUCUOCHOP_NOIDUNG_GetByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUCUOCHOP_NOIDUNG_GetByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_TAILIEUCUOCHOP_FILETAILIEU_GetByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUCUOCHOP_FILETAILIEU_GetByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_LoadYeuCauHoTroByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadYeuCauHoTroByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_LoadLayYKienPhongHopByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_LoadLayYKienPhongHopByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GetDSThongKeCuocHop(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetDSThongKeCuocHop", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_Load_DanhSachChiTietThongKeCuocHop_ByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_DanhSachChiTietThongKeCuocHop_ByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        

        public DataSet LH_YeuCauHoTro_XuLyYeuCau_Upd(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_YeuCauHoTro_XuLyYeuCau_Upd", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_YeuCauHoTro_Del(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_YeuCauHoTro_Del", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_DanhSachNguoiNhanThongBao_ByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DanhSachNguoiNhanThongBao_ByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_DanhSachNguoiNhanThongBaoPhatHanh_ByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DanhSachNguoiNhanThongBaoPhatHanh_ByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_DanhSachNguoiNhanThongBaoSuaLichHop_ByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DanhSachNguoiNhanThongBaoSuaLichHop_ByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_DanhSachNguoiNhanThongBaoPhatBieu_ByLichHopID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DanhSachNguoiNhanThongBaoPhatBieu_ByLichHopID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Them_LHThuMuc(string objJson, int userID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_ThemThuMuc", objJson, userID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Update_LHThuMuc(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateThuMuc", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Delete_LHThuMuc(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DeleteThuMuc", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }


        public DataSet Load_ListThuMuc(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("GetAll_ListThuMuc", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_GetDSTaiLieuKhac(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetDSTaiLieuKhac", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }


        public DataSet LH_GetDSTaiLieuKhacV2(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetDSTaiLieuKhacV2", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet Load_ListTenTaiLieu(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("GetAll_ListTaiLieuKhac", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_TAILIEUKHACV2_InsUpDel(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_TAILIEUKHACV2_InsUpDel", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_ThemTaiLieuKhac(string objJson, int userID)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_ThemTaiLieuKhac", objJson,userID);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_Load_DanhSachChiTietBieuQuyetTuDo_ByBieuQuyetID(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_Load_DanhSachChiTietBieuQuyetTuDo_ByBieuQuyetID", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        
        public DataSet LH_UpdateFileTaiLieuKhac(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateFileTaiLieuKhac", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_UpdateTaiLieuKhac(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateTaiLieuKhac", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_DeleteTaiLieuKhac(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DeleteTaiLieuKhac", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }




        public DataSet LH_GetDSBieuQuyetTuDo(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_GetDSBieuQuyetTuDo", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_ThemBieuQuyetTuDo(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_ThemBieuQuyetTuDo", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_UpdateBieuQuyetTuDo(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_UpdateBieuQuyetTuDo", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }

        public DataSet LH_DeleteBieuQuyetTuDo(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_DeleteBieuQuyetTuDo", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
        public DataSet LH_CheckThoiGianChuongTrinhHop(string objJson)
        {
            try
            {
                return PhongHopKhongGiayDatabase.ExecuteDataSet("LH_CheckThoiGianChuongTrinhHop", objJson);
            }
            catch (Exception ex)
            {
                return new DataSet();
            }
        }
    }
}

