//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by HTT23 at BU5-HIEUTT23 on 07/03/2014 11:47:50 
//====================================================================================================

using System;
using System.ServiceModel;
using System.Data;
using PhongHopKhongGiay.SRV.Entities;
using System.Collections.Generic;

namespace PhongHopKhongGiay.SRV.Services.Contracts
{
    /// <summary>
    /// Service contract for DanhMucService.
    /// </summary>
    [ServiceContract]
    public interface IPhongHopKhongGiayService
    {
        [OperationContract]
        List<DANHMUC> Load_DanhMuc(string Table);

        [OperationContract]
        DataSet Load_USER_GetAllUsers(string ObjJson);
       
        [OperationContract]
        List<THANHPHANCHUANBI> Load_ThanhPhanChuanBi(string Table);

        [OperationContract]
        DataSet LH_Load_DanhSachTaiLieuCuocHopByLichHopID(long? LichHopID, string DoiTuongXemID);

        [OperationContract]
        DataSet Load_DanhSachTaiLieuByTempID(string IDTemp);

        [OperationContract]
        DataSet CN_TAILIEU_UpdateLichHopIDByIDTemp(long? LichHopID,string IDTemp);

        [OperationContract]
        DataSet CN_TAILIEU_InsUpDel(string objJsonTaiLieu);

        [OperationContract]
        DataSet LH_TAILIEUCUOCHOP_InsUpDel(string objJsonTaiLieu);

        [OperationContract]
        DataSet LH_LichHop_InsUpDel(string objJsonLichHop, string DoiTuongNhacLichHopID, string JsonThanhPhan, string JsonChuanBi);

        [OperationContract]
        DataSet LH_ChuyenDuyet(string objJson);

        [OperationContract]
        DataSet CN_Load_DanhSachTaiLieuByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_LoadLichHopByLichHopID(string LichHopID);

        [OperationContract]
        DataSet LH_Load_Schedule(string objJson);

        [OperationContract]
        DataSet LH_Load_Schedule_CaNhan(string objJson);

        [OperationContract]
        DataSet LH_Load_DanhSach_Schedule(string objJson);
        
        [OperationContract]
        DataSet LH_ChuongTrinhHop_InsUpDel(string objJson);


        [OperationContract]
        DataSet LH_BieuQuyet_InsUpDel(string objJson);

        [OperationContract]
        DataSet DM_DANHMUC_InsUpDel(string objJson, string TenStore);

        [OperationContract]
        DataSet LH_LoadBieuQuyetByLichHopID(string LichHopID);


        [OperationContract]
        DataSet LH_UpdateTinhTrangByLichHopID(string objJsonLichHop);

        [OperationContract]
        DataSet LH_UpdateTinhTrangByChuoiLichHopID(string objJsonLichHop);

        [OperationContract]
        DataSet LH_UpdateTinhTrangBatDauHoacKetThucLichHop(string objJsonLichHop);

        [OperationContract]
        DataSet LH_UpdateTinhTrangPhatHanhByTaiLieuKetLuanID(string objJsonLichHop);

        
        [OperationContract]
        DataSet LH_UpdateTimeDragAndDropSchedule(string objJsonLichHop);

        [OperationContract]
        DataSet LH_UpdateShowShowKiosk(string objJsonLichHop);

        [OperationContract]
        DataSet LH_LoadDataTable(string objJson);

        [OperationContract]
        DataSet LH_CheckTrungLichHopByUserID(string objJson);

        [OperationContract]
        DataSet LH_GetPhongBanSuDung(string objJson);

        [OperationContract]
        DataSet LH_GetNguoiChuTriDangDieuHanhCuocHop(string objJson);


        [OperationContract]
        DataSet LH_LoadChuongTrinhHopByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_THAOLUAN_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_LoadThaoLuanByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_GIAYMOIHOP_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_LoadGiayMoiHopByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_GetEmailThanhPhanThamDuTheoThoiGian(string objJson);

        [OperationContract]
        DataSet LH_PhatHanh_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_LoadPhatHanhByThoiGian(string objJson);

        [OperationContract]
        DataSet LH_LoadNoiDungInAnTheoThoiGian(string objJson);

        [OperationContract]
        DataSet LH_GetLichHopIDTheoThoiGian(string objJson);
 
        [OperationContract]
        DataSet LH_PhatHanhLichHopID(string objJson);
        [OperationContract]
        DataSet LH_LoadPhatHanhLichSuTheoThoiGian(string objJson);

        [OperationContract]
        DataSet LH_PhatHanhTrucTiep(string objJson);


        [OperationContract]
        DataSet Mobile_LH_LICHHOP_BAOVANG_Upd(int LichHopID,int UserID, int LyDoID,string NoiDungLyDo);


        [OperationContract]
        DataSet Mobile_LH_LICHHOP_XUNGDOT_Upd(int LichHopID, int UserID, int LyDoID, string NoiDungLyDo);

        [OperationContract]
        DataSet Mobile_LH_LICHHOP_CHAPNHAN_Upd(int LichHopID, int UserID);


        [OperationContract]
        DataSet Mobile_LH_LICHHOP_TUCHOIHOP_Upd(int LichHopID, int UserID, int LyDoID, string NoiDungLyDo);

        [OperationContract]
        DataSet Mobile_LH_BIEUQUYET_KETQUA_Ins(int UserID, int BieuQuyetID, bool DongY);

        [OperationContract]
        DataSet LH_BIEUQUYET_GetByLichHopID(int LichHopID,int PageSize, int PageIndex,int UserID);

        [OperationContract]
        DataSet CN_Load_DanhSachTaiLieuByUserID(int UserID, long LichHopID);

        [OperationContract]
        DataSet Mobile_CN_TAILIEU_Ins(int UserID, int TaiLieuCuocHopID, long LichHopID);

        [OperationContract]
        DataSet Mobile_CN_TAILIEU_CHIASE_Ins(int NguoiChiaSeID, int NguoiNhanChiaSeID, long TaiLieuChiaSeID);

        [OperationContract]
        DataSet LH_UpdateTinhTrangCuocHop(int BieuQuyetID, bool TinhTrang, bool DaKetThuc, long UserID);

        [OperationContract]
        DataSet LH_LoadDangKyPhatBieuTheoLichHopID(int LichHopID, long UserID);

        [OperationContract]
        DataSet LH_DANGKYPHATBIEU_InsUpDel(string obj);

        [OperationContract]
        DataSet LH_UpdateDoUuTienDangKyPhatBieu(string ChuoiDangKyPhatBieuID);

        [OperationContract]
        DataSet LH_UPDATE_THOIGIAN_DANGKYPHATBIEU (string obj);

        [OperationContract]
        DataSet LH_LoadBienBanHopByLichHopID(string objJson);


        [OperationContract]
        DataSet LH_BIENBANHOP_InsUpDel (string objJson);


        [OperationContract]
        DataSet LH_GiaoViec_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_GiaoViec_UpdateChiTietGiaoViec(string objJson);

        [OperationContract]
        DataSet LH_LoadGiaoViecTheoLichHopID(string objJson);


        [OperationContract]
        DataSet LH_NOIDUNG_IN_AN_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_TRIGGER_SIGNALR(string objJson);

        [OperationContract]
        DataSet LH_InLichHopTheoTuan(string objJson);

        [OperationContract]
        DataSet LH_LoadChiTietBieuQuyetKetQuaTheoBieuQuyetID(int BieuQuyetID);

        [OperationContract]
        DataSet LH_InKetLuanTheoLichHopID(int LichHopID);

        [OperationContract]
        DataSet Mobile_LH_LICHHOP_DUYETBAOVANG_Upd(int LichHopID, int UserID, bool DuyetBaoVang, string LyDoKhongDuyet);

        [OperationContract]
        DataSet LH_TAILIEUKETLUAN_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_CheckRoleByUserID(int UserID);

        [OperationContract]
        DataSet LH_TAILIEUCUOCHOP_COQUANCHUTRI_GetByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_TAILIEUCUOCHOP_NOIDUNG_GetByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_TAILIEUCUOCHOP_FILETAILIEU_GetByLichHopID(string objJson);


        [OperationContract]
        DataSet LH_LoadYeuCauHoTroByLichHopID(string objJson);
        [OperationContract]
        DataSet LH_YeuCauHoTro_XuLyYeuCau_Upd(string objJson);
        [OperationContract]
        DataSet LH_YeuCauHoTro_Del(string objJson);

        [OperationContract]
        DataSet LH_LoadLayYKienPhongHopByLichHopID(string objJson);


        [OperationContract]
        DataSet LH_DanhSachNguoiNhanThongBao_ByLichHopID(string objJsonLichHop);

        [OperationContract]
        DataSet LH_GetDSThongKeCuocHop(string objJson);


        [OperationContract]
        DataSet LH_Load_DanhSachChiTietThongKeCuocHop_ByLichHopID(string objJson);


        [OperationContract]
        DataSet LH_DanhSachNguoiNhanThongBaoPhatHanh_ByLichHopID(string objJson);

        [OperationContract]
        DataSet LH_DanhSachNguoiNhanThongBaoSuaLichHop_ByLichHopID(string objJsonLichHop);

        [OperationContract]
        DataSet LH_DanhSachNguoiNhanThongBaoPhatBieu_ByLichHopID(string objJson);

        [OperationContract]
        DataSet Them_LHThuMuc(string objJson, int userID);

        [OperationContract]
        DataSet Update_LHThuMuc(string objJson);

        [OperationContract]
        DataSet Delete_LHThuMuc(string objJson);

        [OperationContract]
        DataSet Load_ListThuMuc(string objJson);

        [OperationContract]
        DataSet LH_GetDSTaiLieuKhac(string objJson);

        [OperationContract]
        DataSet LH_GetDSTaiLieuKhacV2(string objJson);

        [OperationContract]
        DataSet Load_ListTenTaiLieu(string objJson);

        [OperationContract]
        DataSet LH_TAILIEUKHACV2_InsUpDel(string objJson);

        [OperationContract]
        DataSet LH_ThemTaiLieuKhac(string objJson,int userID);
        
        [OperationContract]
        DataSet LH_UpdateFileTaiLieuKhac(string objJson);

        [OperationContract]
        DataSet LH_UpdateTaiLieuKhac(string objJson);

        [OperationContract]
        DataSet LH_DeleteTaiLieuKhac (string objJson);

        [OperationContract]
        DataSet LH_GetDSBieuQuyetTuDo(string objJson);

        [OperationContract]
        DataSet LH_Load_DanhSachChiTietBieuQuyetTuDo_ByBieuQuyetID(string objJson);

        [OperationContract]
        DataSet LH_ThemBieuQuyetTuDo(string objJson);

        [OperationContract]
        DataSet LH_UpdateBieuQuyetTuDo(string objJson);

        [OperationContract]
        DataSet LH_DeleteBieuQuyetTuDo(string objJson);

        [OperationContract]
        DataSet LH_CheckThoiGianChuongTrinhHop(string objJson);
    }
}
