//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongHopKhongGiay.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Get_DataReport", ReplyAction="http://tempuri.org/IReportService/Get_DataReportResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PhongHopKhongGiay.ReportService.Get_DataReportResponse Get_DataReport(PhongHopKhongGiay.ReportService.Get_DataReportRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/Get_DataReport", ReplyAction="http://tempuri.org/IReportService/Get_DataReportResponse")]
        System.Threading.Tasks.Task<PhongHopKhongGiay.ReportService.Get_DataReportResponse> Get_DataReportAsync(PhongHopKhongGiay.ReportService.Get_DataReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_DataReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_DataReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ReportCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int DonViID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public object[] Params;
        
        public Get_DataReportRequest() {
        }
        
        public Get_DataReportRequest(string ReportCode, int DonViID, object[] Params) {
            this.ReportCode = ReportCode;
            this.DonViID = DonViID;
            this.Params = Params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_DataReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Get_DataReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Get_DataReportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string table;
        
        public Get_DataReportResponse() {
        }
        
        public Get_DataReportResponse(string Get_DataReportResult, string table) {
            this.Get_DataReportResult = Get_DataReportResult;
            this.table = table;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : PhongHopKhongGiay.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<PhongHopKhongGiay.ReportService.IReportService>, PhongHopKhongGiay.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhongHopKhongGiay.ReportService.Get_DataReportResponse PhongHopKhongGiay.ReportService.IReportService.Get_DataReport(PhongHopKhongGiay.ReportService.Get_DataReportRequest request) {
            return base.Channel.Get_DataReport(request);
        }
        
        public string Get_DataReport(string ReportCode, int DonViID, object[] Params, out string table) {
            PhongHopKhongGiay.ReportService.Get_DataReportRequest inValue = new PhongHopKhongGiay.ReportService.Get_DataReportRequest();
            inValue.ReportCode = ReportCode;
            inValue.DonViID = DonViID;
            inValue.Params = Params;
            PhongHopKhongGiay.ReportService.Get_DataReportResponse retVal = ((PhongHopKhongGiay.ReportService.IReportService)(this)).Get_DataReport(inValue);
            table = retVal.table;
            return retVal.Get_DataReportResult;
        }
        
        public System.Threading.Tasks.Task<PhongHopKhongGiay.ReportService.Get_DataReportResponse> Get_DataReportAsync(PhongHopKhongGiay.ReportService.Get_DataReportRequest request) {
            return base.Channel.Get_DataReportAsync(request);
        }
    }
}
